apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: camel-hello-minikube
  name: camel-hello-minikube
  namespace: first-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: camel-hello-minikube
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: camel-hello-minikube
    spec:
      containers:
        - image: {REGISTRY}/apress/camel-hello-minikube:1.0.0
          imagePullPolicy: IfNotPresent
          name: camel-hello-minikube
          ports:
            - containerPort: 8080
              protocol: TCP